### PR TITLE
Initial work on TSLint rule set for JSDoom

### PR DESCRIPTION
**Pull request by Talon1024**
Add tslint to package.json, and "lint" script to invoke tslint
Add WIP tslint.json based on the code style guide

### CODE REVIEW

**Comment by pineapplemachine** [comment]
This PR looks good. I would want to take some time to read about the specific rule config choices in more detail, but from what I see so far I think this works. However, I am not certain about adopting TSLint. It is associated with a company whose business practices I believe are very unethical, and though I can't speak from firsthand experience with the tool [I have read that it is not maintained as well as it should be](https://medium.com/@klaus.meinhardt1/tslint-is-dead-31f55c8fce1f).

I am interested in your opinion, especially if you have used TSLint before. Do you think that TSLint is a good tool? How would you feel about using [fimbullinter](https://github.com/fimbullinter/wotan) instead? It appears to be possible to use it [as a drop-in replacement](https://github.com/fimbullinter/wotan/blob/master/packages/valtyr/README.md).

**Comment by Talon1024** [comment]
TSLint has a plugin for [Atom](https://atom.io), and I like that, since the plugin makes it easier to see code style issues in real time. Also, the Angular and React TypeScript project templates use TSLint by default, and not fimbullinter.

However, I'm OK with using fimbullinter. I took a quick look at it, and it doesn't seem to have as many built-in rules as TSLint, so a lot of rules would have to be custom-coded from scratch. But, I do wonder what rock I've been living under to not have heard of fimbullinter...

**Comment by pineapplemachine** [comment]
I'm ok with keeping some subset of linter config that will also work with
tslint IDE plug-ins so that you could continue to use yours with the same
config file. And since I started work on some custom linter code already I
feel pretty comfortable implementing any important but missing rules myself.

I'm out at the moment but I think I will be able to get enough linter work
done this evening to make everything work with the CI, if you could push
one more commit to remove tslint from the dependencies before I merge.
Stupid nitpick, I know, but I'd prefer to not have the dependency in the
master branch history at all. (I *really* don't like Palantir.)

**Comment by Talon1024** [comment]
I just force-pushed a commit to remove the tslint dependency from the package.json file. I left the tslint.json file as is, however.

**Comment by pineapplemachine** [comment]
Ok, awesome. Thanks for working on this. I'm going to merge and see about fixing any lint errors and then making enforcement part of CI.

**Pull request merged**
